
pr:
  branches:
    include:
      - main
      - dev

trigger:
  branches:
    include:
      - main
      - dev
  paths:
     exclude:
       - README.md

stages:
- stage: BuildSpinWheelPackage
  displayName: 'Build Stage spin-wheel-package'
  jobs:
  - job: build_job_spin_wheel_package
    displayName: 'Build Job spin-wheel-package'
    condition: or(eq(variables['Build.Reason'], 'Manual'),or(eq(variables['Build.Reason'], 'PullRequest'),eq(variables['Build.Reason'], 'IndividualCI')))
    steps:
    - task: NodeTool@0
      displayName: 'Install Node.js'
      inputs:
        versionSource: 'spec'
        versionSpec: '18.x'

    - script: |
          npm install
          npm run build
      displayName: 'npm install and build'

#Stage to Deploy to Dev
- stage: DeployDev
  displayName: 'Deploy to Dev'
  jobs:
  - job: deploy_dev_job
    displayName: 'Deploy to Dev Job'
    pool:
      vmImage: ubuntu-latest
    variables:
    - group: Azure-Static-Web-Apps-witty-meadow-00a63c80f-variable-group
    - name: $VITE_FRAME_SRC
      value: 'https://witty-meadow-00a63c80f-dev.eastus2.4.azurestaticapps.net'
    steps:
    - checkout: self
      submodules: true  
    - task: AzureStaticWebApp@0
      inputs:
        azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_MEADOW_00A63C80F)
        app_location: "" # Leave empty to deploy from the root
        api_location: "" # Api source code path - optional     
        output_location: "dist" # Built app content directory
        app_build_command: "" # No additional build command needed as npm run build is already executed
        production_branch: 'main'
      displayName: 'Deploy to Dev'
      env:
        VITE_BETWAY_NJ: 40730
        VITE_JPC_NJ: 40731
        VITE_BETWAY_PA: 40732
        VITE_JPC_PA: 40733
        VITE_IS_MAINTENANCE: false
        VITE_ENVIRONMENT: 'dev'
        VITE_DEV_FUNC_APP: 'https://func-dgc-promo-widget-dev-02.azurewebsites.net'
    condition: and(eq(variables['Build.SourceBranch'], 'refs/heads/dev'), ne(variables['Build.Reason'], 'PullRequest'))

#Stage to Deploy to Prod
- stage: DeployProd
  displayName: 'Deploy to Prod'
  jobs:
    - job: deploy_prod_job
      displayName: 'Deploy to Prod Job'
      pool:
        vmImage: ubuntu-latest
      variables: 
      - group: Azure-Static-Web-Apps-witty-meadow-00a63c80f-variable-group
      - name: $VITE_ENV
        value: production
      steps:
      - checkout: self
        submodules: true
          
      - task: AzureStaticWebApp@0
        inputs:
          azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_MEADOW_00A63C80F)
          app_location: "" # Leave empty to deploy from the root
          api_location: "" # Api source code path - optional     
          output_location: "dist" # Built app content directory
          app_build_command: "" # No additional build command needed as npm run build is already executed
        displayName: 'Deploy to Prod'
        env:
          VITE_ENV: 'production'
          VITE_BETWAY_NJ: 40730
          VITE_JPC_NJ: 40731
          VITE_BETWAY_PA: 40732
          VITE_JPC_PA: 40733
          VITE_IS_MAINTENANCE: false
          VITE_ENVIRONMENT: 'prod'
          VITE_PROD_FUNC_APP: 'https://promo-widget-api.dgcops.net'
      condition: and(eq(variables['Build.SourceBranch'], 'refs/heads/main'), ne(variables['Build.Reason'], 'PullRequest'))
